apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    kubernetes.io/metadata.name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-001
  namespace: demo
  labels:
    app.kubernetes.io/managed-by: demo
spec:
  selector:
    matchLabels:
      app: test-001
  replicas: 1
  template:
    metadata:
      labels:
        app: test-001
    spec:
      containers:
        - name: busybox
          image: docker.io/library/busybox:latest

